/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_android_myndktest_NdkJniUtils */

#ifndef _Included_com_demo_android_myndktest_NdkJniUtils
#define _Included_com_demo_android_myndktest_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_android_myndktest_NdkJniUtils
 * Method:    getCLanguaeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demo_android_myndktest_NdkJniUtils_getCLanguaeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
